# Generated by Django 4.2 on 2023-11-16 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_delete_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_fields', models.JSONField(default=dict)),
                ('event', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
