# Generated by Django 4.2 on 2023-12-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organizer_id',
            new_name='organizer',
        ),
        migrations.AlterField(
            model_name='event_form',
            name='event',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='event_form', to='events.event'),
        ),
    ]
