# Generated by Django 4.2 on 2023-12-28 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_rename_organizer_id_event_organizer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(default='event_cover_images/default.jpg', upload_to='event_cover_images/'),
        ),
    ]
