# Generated by Django 4.2 on 2023-12-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_image',
            field=models.ImageField(default='event_cover_images/default.jpg', upload_to='event_cover_images/'),
        ),
    ]
