# Generated by Django 4.2 on 2024-04-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
