version: '1.1'
services:
    web:
        build: ./backend
        command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - ./backend/:/usr/src/backend/
            - static_volume:/home/getit/backend/static
            - media_volume:/home/getit/backend/media
        expose:
            - 8000
        env_file:
            - ./backend/.env
        depends_on:
            - db
    db:
        image: postgres:15
        volumes:
            - postgres_data:/var/lib/postgresql/data
        env_file:
            - ./backend/.env.prod.db
    frontend:
        build: ./frontend
        command: node .output/server/index.mjs
        expose:
            - 3030
        env_file:
            - ./frontend/.env.prod

    nginx:
        build: ./nginx
        ports:
            - 1337:8080
        volumes:
            - static_volume:/home/getit/backend/static
            - media_volume:/home/getit/backend/media
        depends_on:
            - web
            - frontend
volumes:
    postgres_data:
    static_volume:
    media_volume:
