# Generated by Django 4.2 on 2024-03-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='total',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
