# Generated by Django 4.2 on 2025-06-02 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_seller_product_tags_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='Product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_variations', to='products.product'),
            preserve_default=False,
        ),
    ]
