# Generated by Django 4.1 on 2023-07-13 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productcolor_productsize_productvariation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='primary_variant',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariation'),
        ),
    ]
