# Generated by Django 4.1 on 2023-07-13 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_primary_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
