# Generated by Django 4.1 on 2023-07-13 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productvariation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariation',
            name='cover_image',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productimage'),
        ),
    ]
