# Generated by Django 4.1 on 2023-07-22 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariation_cover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='color_id',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='productvariation',
            old_name='size_id',
            new_name='size',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='product_id',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_variations', to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('rsvp', 'RSVP')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_variant',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='primary_variant', to='products.productvariation'),
        ),
    ]
