# Generated by Django 4.1 on 2023-07-22 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_color_id_productvariation_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='color',
            new_name='ProductColor',
        ),
        migrations.RenameField(
            model_name='productvariation',
            old_name='size',
            new_name='ProductSize',
        ),
        migrations.RemoveField(
            model_name='productvariation',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_variant',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvariation'),
        ),
        migrations.AddField(
            model_name='productvariation',
            name='Product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='products.product'),
            preserve_default=False,
        ),
    ]
