# Generated by Django 4.2 on 2024-03-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('purchased', 'Purchased'), ('failed', 'Purchase Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=100),
        ),
    ]
