# Generated by Django 4.2 on 2024-03-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
